name: publish npm package

on:
  push:
    branches:
      - master

jobs:
  publish-npm-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm link
      - run: npm link cross-rates
      # sleep so monobank api will not fail with "too many requests" after main tests
      - run: npm run test
      - run: npm unlink cross-rates
      - run: npm unlink
      - run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"
      - run: npm version patch --force
      - run: git push --tags && git push
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  publish-browser-client:
    needs: publish-npm-module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: cd ./cross-rates-browser
      - run: sleep 60
      - run: npm install
      - run: npm run build
      - run: npm link
      - run: npm link cross-rates-browser
      - run: npm run test
      - run: npm unlink cross-rates-browser
      - run: npm unlink
      - run: npm version patch --force
      - run: cd ../
      - run: git add ./cross-rates-browser/
      - run: git commit -m 'Browser client version updated'
      - run: git push
      - run: cd ./cross-rates-browser
      - run: npm publish --access public
      - run: cd ../
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: error-logs
          path: /home/runner/.npm/_logs





